### ISSUE TITLE
sendTemplate() not working with other types of template except button

### ISSUE THREAD

**Issue by vinhhap** [botpress/botpress-messenger#22]
Here is the payload, i got this from [Facebook doc](https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template)
```
let payload = {
  "template_type":"generic",
  "elements":[
     {
      "title":"Welcome to Peter\'s Hats",
      "image_url":"https://petersfancybrownhats.com/company_image.png",
      "subtitle":"We\'ve got the right hat for everyone.",
      "default_action": {
        "type": "web_url",
        "url": "https://peterssendreceiveapp.ngrok.io/view?item=103",
        "messenger_extensions": true,
        "webview_height_ratio": "tall",
        "fallback_url": "https://peterssendreceiveapp.ngrok.io/"
      },
      "buttons":[
        {
          "type":"web_url",
          "url":"https://petersfancybrownhats.com",
          "title":"View Website"
        },{
          "type":"postback",
          "title":"Start Chatting",
          "payload":"DEVELOPER_DEFINED_PAYLOAD"
        }              
      ]      
    }
  ]
};
```

And when ever I call:

```bp.messenger.sendTemplate(userId, payload, { typing: 2000 });```

I got errors:

> error: Error: An error has been returned by Facebook API.
> Status: 400 (Bad Request)
> (#100) The URL provided is not whitelisted for messenger extensions

**Comment by slvnperron** [comment]
Hi Nguyen,

This error means you haven't whitelisted the URLs in the template in the
"Whitelisted Websites" section of the Messenger module. Closing this :)

**Comment by slvnperron** [comment]
Let me know if this doesn't work and we'll reopen !
