### ISSUE TITLE
GET STARTED payload event is sent twice

### ISSUE THREAD

**Issue by znat** [botpress/botpress-messenger#28]
When setting a payload in the UI for the Get Started event, the following is called twice:

```
bp.hear({ platform: 'facebook', type: 'postback', text : 'GET_STARTED' }, event => {
   //...
});
```

**Comment by slvnperron** [comment]
Yeah I think that is not very user-friendly, but the original 'GET_STARTED' event is always triggered, wether you defined a custom postback or not. The reason it is called twice is that you named it 'GET_STARTED' like the one already fired.

Does that make sense?

**Comment by znat** [comment]
That was exactly it. Thanks
