### ISSUE TITLE
messenger templates not generating images

### ISSUE THREAD

**Issue by tanmoy12** [botpress/botpress-messenger#40]
image: `${process.env.BOT_BASE_URL}/IMG.jpg`

what does this mean? where do i keep the image? is this related to postgresql?

**Comment by slvnperron** [comment]
`process.env.BOT_BASE_URL` is simply an environment variable that points to the public url of your bot (i.e. your server or ngrok hostname). Then `IMG.jpg` is the name of the file you hosted under the `./static` folder at your bot's root.

**Comment by tanmoy12** [comment]
I'm using ngrok hostname, templates show images available in public URLs, 
I don't see a ./static folder. 
What if i wanted to load an image from my PC? 
Thank you for the response.

**Comment by slvnperron** [comment]
You can create a `static` folder in your bot's root folder and put the files you want to host publicly there

**Comment by tanmoy12** [comment]
I tried that. I created a **static** folder and put IMG.jpg file there. 
this is my static_data file: 
    module.exports = {
    cities: [
        { name: 'San Francisco', code: 'SF', image: '${process.env.BOT_BASE_URL}/IMG.jpg' },
        { name: 'New York', code: 'NY', image: '${process.env.BOT_BASE_URL}/IMG.jpg' },
        { name: 'Frankfurt', code: 'FRA', image: '${process.env.BOT_BASE_URL}/IMG.jpg' },
        { name: 'Budapest', code: 'BUD', image: '${process.env.BOT_BASE_URL}/IMG.jpg' },
        { name: 'Kuala Lumpur', code: 'KL', image: '${process.env.BOT_BASE_URL}/IMG.jpg' }
    ]
    }

I'm getting an error : 
       error: [BOTPRESS] Unhandled error in middleware (outgoing). Error: An error has been returned by Facebook API.
Status: 400 (Bad Request)
(#100) [elements][0][image_url] should represent a valid URL

**Comment by slvnperron** [comment]
But have you defined BOT_BASE_URL ?

**Comment by tanmoy12** [comment]
No i haven't . how do i do it?

**Comment by slvnperron** [comment]
It's an [environment variable](https://medium.com/@rafaelvidaurre/managing-environment-variables-in-node-js-2cb45a55195f). Simply make it the URL of your bot, for example your heroku url or your ngrok url.

**Comment by tanmoy12** [comment]
I read through the article.
ngrok seems to generate URLs dynamically everytime i run **bp start**, so i could not set the URL beforehand,

Are there any tutorials on setting environment variables? 
It will be very helpful, thank you.

**Comment by slvnperron** [comment]
I use [pagekite](pagekite.net) which works much more reliably and give me a static url
