### ISSUE TITLE
Error: Connection is disabled, look to your config and set enabled to true if you want to connect your bot

### ISSUE THREAD

**Issue by ariskemper** [botpress/botpress-messenger#44]
In a new fresh installation of our bot, we get this error:

Error: Connection is disabled, look to your config and set enabled to true, if you want to connect your bot.
The botpress-messenger.config.yaml is created on first start of the bot. If, we setle the configuration via botpress gui, we get another error on saving:

Details: An error has been returned by Facebook API. Status: 400 (Bad Request) (#194) Requires all or none of the params: callback_url, verify_token

    "botpress": "1.0.13",
    "botpress-messenger": "2.1.4"

**Comment by slvnperron** [comment]
Thanks @ariskemper , will have a look

**Comment by slvnperron** [comment]
@ariskemper Fixed
