### ISSUE TITLE
how allow all facebook users use my app?

### ISSUE THREAD

**Issue by hoangweb** [botpress/botpress-messenger#48]
i have to public my facebook app, & deplpoy botpress on heroku, my account worked & add tester user that worked. But i want any user in facebook should work? how?

**Comment by m0rth1um** [comment]
You have to request the 'pages_messaging' submission on the Facebook developers page. Go to the settings of your page on https://developers.facebook.com, then choose 'Messenger' in the left menu and then scroll down to 'App Review for Messenger'.

**Comment by hoangweb** [comment]
thank you!
