### ISSUE TITLE
why all users use share conversation?

### ISSUE THREAD

**Issue by hoangweb** [botpress/botpress-messenger#49]
i need each users has private conversation.
`bp.convo.start(event, convo => {
	const defaultThread = convo.threads['default'] ;
	//cause share conversation between many fb users
	defaultThread.addQuestion('#quest1',[
		{
			default: true,
			callback: (response) => {}
		}
	])
	//or use this
	convo.ask(message, function(response, convo) { /* ... */ })
})`

**Comment by slvnperron** [comment]
Duplicate
