### ISSUE TITLE
Error setting trusted domains - The parameter fields is required

### ISSUE THREAD

**Issue by akapei** [botpress/botpress-messenger#62]
I have had my bot working for about 6 months now and all of a sudden I have been getting this error:

`Error: Error setting trusted domains
An error has been returned by Facebook API.
Status: 400 (Bad Request)
(#100) The parameter fields is required
at /root/bot/node_modules/botpress-messenger/bin/webpack:/src/messenger.js:482:13
23:42:07 - error: [notification::botpress] Error updating Messenger App. Please see logs for details.`

**Comment by slvnperron** [comment]
It happened about 3 times in the past that Facebook updates and broke their
API without advising anybody. Will look into it tomorrow.

**Comment by akapei** [comment]
That old chestnut. Yeah, it's happened to me on other apps too. I was posting in case it was a known issue. I can have a look too to see if I can't figure it out.

**Comment by chrisribe** [comment]
Ahhh well that explains why I have been trying to get this to work for 3 hours !!!
Please advise when you figure it out.

Thanks!

**Comment by jsalwen** [comment]
@slvnperron I will do a PR for this

**Comment by saitai0802** [comment]
Thank you guys, Has this fix been released to the master already?

**Comment by jsalwen** [comment]
@saitai0802 I believe so

**Comment by saitai0802** [comment]
But I still got this error, do you know what made this happened?
Version List:
`09:37:18 - info: Starting botpress version 1.1.11
09:37:20 - info: Loaded botpress-api.ai, version 2.1.7
09:37:20 - info: Loaded botpress-hitl, version 1.0.10
09:37:20 - verbose: [UMM] Enabled for facebook
09:37:20 - info: Loaded botpress-messenger, version 2.2.9
09:37:20 - verbose: [UMM] Enabled for web
09:37:20 - info: Loaded botpress-web, version 1.2.3`

Error:
`09:37:20 - info: Bot launched. Visit: http://localhost:3000
09:37:26 - error:  Error: Error setting trusted domains
An error has been returned by Facebook API.
Status: 400 (Bad Request)
(#100) The parameter fields is required
    at /my_root/bin/webpack:/src/messenger.js:482:13
    at <anonymous>
09:37:26 - error: [notification::botpress] Error updating Messenger App. Please see logs for details.`

**Comment by saitai0802** [comment]
i am wondering if Facebook updates something again without notice anyone

**Comment by jsalwen** [comment]
@slvnperron please deploy the latest version of `botpress-messenger` to npm

@saitai0802 it looks like `2.2.9` does not contain the fix, for now you can install the package from github
```
npm i --save https://github.com/botpress/botpress-messenger
```

**Comment by saitai0802** [comment]
thank you @jsalwen 
After running the line you provided above.
my package.json file changed the line to 
`botpress-messenger": "git+https://github.com/botpress/botpress-messenger.git"`

and the botpress-messenger folder inside my botpress folder removed a bin folder. Then I can't see the botpress-messenger in the sidebar inside my botpress platform.

During the installation, there was a error:
[root@localhost MyRoot]# npm i --save https://github.com/botpress/botpress-messenger
npm WARN react-codemirror@1.0.0 requires a peer of react@>=15.5 <16 but none is installed. You must install peer dependencies yourself.
npm WARN react-codemirror@1.0.0 requires a peer of react-dom@>=15.5 <16 but none is installed. You must install peer dependencies yourself.
npm WARN react-jsonschema-form@0.49.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-audio-player@0.5.0 requires a peer of react@15.x but none is installed. You must install peer dependencies yourself.
npm WARN react-audio-player@0.5.0 requires a peer of react-dom@15.x but none is installed. You must install peer dependencies yourself.
npm WARN react-player@0.18.0 requires a peer of react@* but none is installed. You must install peer dependencies yourself.
npm WARN my_chatbot@0.0.1 No description
npm WARN my_chatbot@0.0.1 No repository field.
npm WARN my_chatbot@0.0.1 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: assert-plus@1.0.0 (node_modules/fsevents/node_modules/dashdash/node_modules/assert-plus):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/my_root/node_modules/fsevents/node_modules/dashdash/node_modules/assert-plus/package.json.1805164643'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: assert-plus@1.0.0 (node_modules/fsevents/node_modules/getpass/node_modules/assert-plus):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/my_chatbot/node_modules/fsevents/node_modules/getpass/node_modules/assert-plus/package.json.1752823902'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@1.2.0 (node_modules/fsevents/node_modules/rc/node_modules/minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/vagrant/botpress-sandbox/FindDocChatBot/node_modules/fsevents/node_modules/rc/node_modules/minimist/package.json.3827013866'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: assert-plus@1.0.0 (node_modules/fsevents/node_modules/sshpk/node_modules/assert-plus):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/my_chatbot/node_modules/fsevents/node_modules/sshpk/node_modules/assert-plus/package.json.655900011'

**Comment by saitai0802** [comment]
update: just found that was a bug inside my /index.js file. but still, even my chatbot works perfectly with api.ai and messenger. There is still an error when run
`botpress start`

Error:
09:37:20 - info: Bot launched. Visit: http://localhost:3000
09:37:26 - error: Error: Error setting trusted domains
An error has been returned by Facebook API.
Status: 400 (Bad Request)
(#100) The parameter fields is required
at /my_root/bin/webpack:/src/messenger.js:482:13
at 09:37:26 - error: [notification::botpress] Error updating Messenger App. Please see logs for details.

**Comment by gcfabri** [comment]
Still facing issues with Facebook API. Clean installation and latest published packages.

```
"dependencies": {
    "botpress": "^1.1.12",
    "botpress-messenger": "^2.2.9",
    "botpress-web": "^1.2.3"
}
```

```
> botpress start

14:20:35 - info: Starting botpress version 1.1.11
14:20:35 - verbose: [UMM] Enabled for facebook
14:20:35 - info: Loaded botpress-messenger, version 2.2.9
14:20:35 - verbose: [UMM] Enabled for web
14:20:35 - info: Loaded botpress-web, version 1.2.3
14:20:35 - info: Loaded 2 modules
14:20:35 - debug: Loading middleware: UMM.instrumentation
14:20:35 - debug: Loading middleware: hear
14:20:35 - debug: Loading middleware: conversations
14:20:35 - debug: Loading middleware: messenger.sendMessages
14:20:35 - debug: Loading middleware: web.sendMessages
14:20:35 - debug: Loading middleware: fallback
14:20:35 - info: Bot launched. Visit: http://localhost:3000
14:20:38 - error:  Error: Error setting trusted domains
An error has been returned by Facebook API.
Status: 400 (Bad Request)
(#100) The parameter fields is required
    at /home/gcfabri/Workspace/XXX/node_modules/botpress-messenger/bin/webpack:/src/messenger.js:482:13
    at <anonymous>
14:20:39 - error: [notification::botpress] Error updating Messenger App. Please see logs for details.
```

**Comment by jsalwen** [comment]
@saitai0802 @gcfabri 
The `2.2.9` version of `botpress-messenger` on `npm` does not contain the latest code, so it does not fix the trusted domain issue.

Once the new version of the module is published to `npm`, then you can use npm or yarn to install/update the module.

Until then, you will have to install from github. 
```shell
npm uninstall botpress-messenger --save
npm install https://github.com/botpress/botpress-messenger --save
```
note: I believe the version will be `2.2.8` if you install from github
```shell
10:01:32 info: Loaded botpress-messenger, version 2.2.8
```

@slvnperron when will `botpress-messenger` be published to `npm`?

**Comment by to7be** [comment]
Thank you @jsalwen. This worked for me!

**Comment by slvnperron** [comment]
Hey guys, I've just published the latest version to npm. You can now install it with `npm install botpress-messenger`. The version is `2.2.10`.

Thanks @jsalwen for the fix, apologies in delay publishing this change.

**Comment by mrbarletta** [comment]
thanks @slvnperron  its working now :)

**Comment by surya103** [comment]
Hi, I still have similar issue.. My botpress-messenger version is 2.2.10
