### ISSUE TITLE
How add persistent menu items in config.yml

### ISSUE THREAD

**Issue by to7be** [botpress/botpress-messenger#74]
How do I handle the property `persistentMenuItems: []` within the `botpress-messenger.config.yml`?

I already tried many different notations and I couldn't find any notes in the documentation. It only mentions:
> Tip: You can also set all the other configs using this configuration file, simply add them and it will override the configuration set in the database.

But there are no further instructions.

When I try adding persistent menu items through the UI, it always put 'undefined' into the value field (even after I correctly saved the page).

**Comment by slvnperron** [comment]
Hi, the payload is identical to what you would normally send the Facebook API 

https://developers.facebook.com/docs/messenger-platform/send-messages/persistent-menu

**Comment by OAyomide** [comment]
in addition to what @slvnperron  said: check out [this gist ](https://gist.github.com/OAyomide/a3eb76e29f7faa2888fe22d48a8c6f70)I made for another person who asked the same question:. Simply remove the values and have fun with botpress!

**Comment by to7be** [comment]
Thank you both so much! Never thought about just inserting the normal payload into the YAML.

**Comment by OAyomide** [comment]
@slvnperron I think you should close this issue.
