### ISSUE TITLE
Botpress x Heroku

### ISSUE THREAD

**Issue by devhaoy** [botpress/botpress-messenger#9]
Hey has anyone set up Botpress with Heroku?

My logs giving me an error "Error: Can't set headers after they are sent." so I am obviously messing up my http requests.

I have set all config variable following the botpress-messenger.json and I could setup the webhook properly. 

I run index.js from the Procfile with a worker dyno. I have this simple express setup in index.js:

```
var express = require('express')
var bodyParser = require('body-parser')
var request = require('request')
var app = express()

app.set('port', (process.env.PORT || 5000))

// Process application/x-www-form-urlencoded
app.use(bodyParser.urlencoded({extended: false}))

// Process application/json
app.use(bodyParser.json())

// Index route
app.get('/', function (req, res) {
    res.send('Hello world')
})

// for Facebook verification
app.get('/api/botpress-messenger/webhook', function (req, res) {
    if (req.query['hub.verify_token'] === '4XXXXX-cXXX-4XXX-3XXX-2XXXXXXX') {
        res.send(req.query['hub.challenge'])
    }
    res.send('Error, wrong token')
})

// Spin up the server
app.listen(app.get('port'), function() {
    console.log('running on port', app.get('port'))
})

module.exports = function(bp) {
  bp.middlewares.load()
}
```

**Comment by slvnperron** [comment]
@devhaoy any reason why you are using a custom express instance instead of using botpress's built-in http server?

I would hint you to change the port in the botfile to `process.env.PORT`

**Comment by devhaoy** [comment]
@slvnperron  thanks I had forgotten Heroku only accepts capital letter PORT, this is why I was setting up my own instance. Now I can connect the webhook using Botpress built-in server, but there is still something I am doing wrong as the bot is not responding (all it does is the automatic answer or shows message as read) and my logs constantly restart the app. 

What should I call in the Procfile? `worker: node index.js ` doesn't work

**Comment by slvnperron** [comment]
cool! Keep in my that the database will reset everyday on heroku as the file system is ephemeral. We're working on a workaround for this

**Comment by eduardoportilho** [comment]
Hey! Whats the plan to workaround this ephemeral file system issue? Can I help to implement it somehow?

**Comment by slvnperron** [comment]
@eduardoportilho yes, we're shipping version `0.1` today with Postgres support, which solves the ephemeral file system issue :)

**Comment by eduardoportilho** [comment]
great! 👏🏻👏🏻👏🏻

**Comment by Reminouche** [comment]
Personally, I use botpress on heroku and everything is fine

**Comment by slvnperron** [comment]
Yes thanks Remi, this has been solved with the introduction of Postgres :)
